name: localizations_sdk
description: A tool for managing Flutter localizations
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  petitparser: 6.1.0
  equatable: 2.0.7
  path_provider: 2.1.5
  package_info_plus: 8.3.0
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  yaml: ^3.1.3
  analyzer: ^7.3.0
  path: ^1.9.0
